version: "3.8"

services:

  backend:
    build:
      context: ${BCK_PATH}
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        BCK_WORKDIR: ${BCK_WORKDIR}
        BCK_PORT: ${BCK_PORT}
    ports:
      - ${BCK_PORT}:${BCK_PORT}
    environment:
      DATABASE_URL: "postgresql://${PSQL_USER}:${PSQL_PSW}@db:${PSQL_PORT}/${PSQL_DB}"
    command: flask run --host=0.0.0.0 --port=${BCK_PORT}

  frontend:
    build:
      context: ${FRNT_PATH}
      args:
        FRNT_PORT: ${FRNT_PORT}
        FRNT_WORKDIR: ${FRNT_WORKDIR}
    ports:
      - ${FRNT_PORT}:${FRNT_PORT}
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV}
    command: ionic serve --host 0.0.0.0 --port ${FRNT_PORT} --disableHostCheck

volumes: