"""Initial migration

Revision ID: d4b55c040ea6
Revises: 
Create Date: 2025-06-06 00:41:12.266738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b55c040ea6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raza',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contacto',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_usuario', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'PROVEEDOR', 'VETERINARIO', 'OTRO', name='tipocontacto'), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_usuario'], ['usuario.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('explotacion',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_usuario'], ['usuario.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('compra',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_contacto', sa.UUID(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uuid_contacto'], ['contacto.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('produccion',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_explotacion', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_explotacion'], ['explotacion.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('venta',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_contacto', sa.UUID(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uuid_contacto'], ['contacto.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('parcela',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_explotacion', sa.UUID(), nullable=False),
    sa.Column('uuid_produccion', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('extension', sa.Float(), nullable=False),
    sa.Column('arrendador', sa.String(length=120), nullable=True),
    sa.Column('coste_arrendamiento', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_explotacion'], ['explotacion.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_produccion'], ['produccion.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('res',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_explotacion', sa.UUID(), nullable=False),
    sa.Column('uuid_progenitor', sa.UUID(), nullable=True),
    sa.Column('uuid_progenitora', sa.UUID(), nullable=True),
    sa.Column('uuid_parcela', sa.UUID(), nullable=True),
    sa.Column('raza_id', sa.UUID(), nullable=True),
    sa.Column('compra_id', sa.UUID(), nullable=True),
    sa.Column('venta_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('especie', sa.Enum('BOVINO', 'OVINO', 'CAPRINO', 'PORCINO', 'EQUINO', 'AVICOLA', 'CONEJO', 'OTRO', name='especie'), nullable=False),
    sa.Column('sexo', sa.Enum('MACHO', 'HEMBRA', name='sexo'), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('fecha_deceso', sa.DateTime(), nullable=True),
    sa.Column('celo', sa.Boolean(), nullable=True),
    sa.Column('fecha_ultimo_parto', sa.DateTime(), nullable=True),
    sa.Column('fecha_preñez', sa.DateTime(), nullable=True),
    sa.Column('numero_identificacion', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.uuid'], ),
    sa.ForeignKeyConstraint(['raza_id'], ['raza.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_explotacion'], ['explotacion.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_parcela'], ['parcela.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_progenitor'], ['res.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_progenitora'], ['res.uuid'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('historial_clinico',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('uuid_res', sa.UUID(), nullable=False),
    sa.Column('uuid_contacto', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('diagnostico', sa.String(length=120), nullable=True),
    sa.Column('tratamiento', sa.String(length=120), nullable=True),
    sa.Column('coste', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uuid_contacto'], ['contacto.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_res'], ['res.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_clinico')
    op.drop_table('res')
    op.drop_table('parcela')
    op.drop_table('venta')
    op.drop_table('produccion')
    op.drop_table('compra')
    op.drop_table('explotacion')
    op.drop_table('contacto')
    op.drop_table('usuario')
    op.drop_table('raza')
    # ### end Alembic commands ###
